---
# tasks file for setup
- name: remove legacy docker
  package:
    name:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
    state: absent
  when: ansible_distribution == 'Ubuntu'

- name: install docker
  apt:
    name:
    - unzip
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - docker.io
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: add ubuntu to docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes

- name: get kubectl
  get_url:
    url: https://dl.k8s.io/release/v1.20.5/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: "0755"