services=[
  "servicemanagement.googleapis.com",
  "servicecontrol.googleapis.com",
  "container.googleapis.com",
  "gkeconnect.googleapis.com",
  "gkehub.googleapis.com",
  "cloudresourcemanager.googleapis.com",
  "anthos.googleapis.com"
]
project_id="kenthua-dev"
