---
# tasks file for roles/wipe
- name: wipe drives
  shell: |
    echo "d
    3
    d
    2
    d

    w" | sudo fdisk /dev/nvme0n1
  when: confirmation | bool

- name: reboot nodes
  command: /sbin/shutdown -r now
  async: true
  poll: 0
  ignore_unreachable: true
  when: confirmation | bool

- name: wait for hosts to be unavailable
  local_action:
    module:  wait_for
    host: "{{ ansible_host }}"
    port: 22
    state: stopped
  when: confirmation | bool

- name: remove current hosts from known_hosts
  become: false
  known_hosts:
    name: "{{ ansible_host }}"
    state: absent
  delegate_to: localhost
  when: confirmation | bool

- name: wait for 1100 seconds
  wait_for:
    timeout: 1100
  delegate_to: localhost
  when: confirmation | bool
