---
# tasks file for roles/check
- name: loop until hostname is 'node', which means ready
  setup:
    gather_subset: facter
  register: result
  until: result.stdout.ansible_facts.ansible_env.HOSTNAME == 'node'
  retries: 5
  delay: 300
  tags: [ 'never', 'special' ]
