---
- hosts: nodes
  gather_facts: false
  tasks:
  - name: wakeup
    wakeonlan:
      mac: "{{ hostvars[inventory_hostname].mac }}"
      broadcast: "{{ ansible_host }}"
    delegate_to: localhost

  - name: Sleep for 90 seconds and continue with play
    wait_for:
      timeout: 90
    delegate_to: localhost

- hosts: controlplane
  gather_facts: false
  tasks:
  - name: wakeup
    wakeonlan:
      mac: "{{ hostvars[inventory_hostname].mac }}"
      broadcast: "{{ ansible_host }}"
    delegate_to: localhost
