---
# parted module is not sufficient, as it deletes partition, but drive still bootable
# reboot module expects the machine to comeback, but while it's installing the key may be different
- name: wipe the hosts
  hosts: all
  gather_facts: false
  become: true
  remote_user: ubuntu
  vars_prompt:
  - name: confirmation
    prompt: "Are you sure you want to wipe? (true/false)"
    private: no

  tasks: 
  - name: wipe drives
    shell: |
      echo "d
      3
      d
      2
      d

      w" | sudo fdisk /dev/nvme0n1
    when: confirmation

  - name: reboot nodes
    command: /sbin/shutdown -r now
    async: true
    poll: 0
    ignore_unreachable: true
    when: confirmation

  - name: wait for hosts to be unavailable
    local_action:
      module:  wait_for
      host: "{{ ansible_host }}"
      port: 22
      state: stopped
    when: confirmation

  - name: remove current hosts from known_hosts
    become: false
    known_hosts:
      name: "{{ ansible_host }}"
      state: absent
    delegate_to: localhost
    when: confirmation

  - name: wait for 1100 seconds
    wait_for:
      timeout: 1100
    delegate_to: localhost
    when: confirmation

- name: check the hosts are empty/ready
  hosts: all
  gather_facts: true
  remote_user: ubuntu
  roles:
  - check
